#if !canImport(ObjectiveC)
import XCTest

extension FileHandleDataHandlerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileHandleDataHandlerTests = [
        ("testHandleData", testHandleData),
    ]
}

extension ProcessOperationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProcessOperationTests = [
        ("testCancel", testCancel),
        ("testExecutableDoesNotExist", testExecutableDoesNotExist),
        ("testOperationSuccess", testOperationSuccess),
        ("testStandardErrorDataHandler", testStandardErrorDataHandler),
        ("testStandardOutputDataHandler", testStandardOutputDataHandler),
    ]
}

extension ShCommandTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ShCommandTests = [
        ("testInitializeWithCommand", testInitializeWithCommand),
        ("testSetCommand", testSetCommand),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FileHandleDataHandlerTests.__allTests__FileHandleDataHandlerTests),
        testCase(ProcessOperationTests.__allTests__ProcessOperationTests),
        testCase(ShCommandTests.__allTests__ShCommandTests),
    ]
}
#endif
